name: up_style
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1  
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  dartz:
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  ionicons: ^0.2.2
  eva_icons_flutter: ^3.1.0
  smooth_corner_updated: ^1.0.0
  hugeicons: ^0.0.7
  equatable: ^2.0.7 
  lottie: ^3.2.0
  modal_bottom_sheet: ^3.0.0
  wolt_modal_sheet: ^0.10.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.3
  go_router: ^14.6.2
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  package_info_plus: ^8.3.0
  infinite_scroll_pagination: ^4.1.0
  dio_smart_retry: ^5.0.0
  http: ^1.3.0
  flutter_image_compress: ^2.4.0
  image: ^4.0.0
  intl: ^0.19.0
  figma_squircle: ^0.6.3
  share_plus: ^10.1.4
  flutter_cache_manager: ^3.3.1
  crypto: ^3.0.3
  system_info_plus: ^0.0.6
  google_sign_in: ^6.3.0
  flutter_localizations:
   sdk: flutter
  path_provider: ^2.1.5
  light_compressor: ^2.2.0
  palette_generator: ^0.3.3+6
  uuid: ^4.5.1
  bloc: ^8.1.4
  firebase_core: ^4.0.0 
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  google_generative_ai: ^0.4.7
  timeago: ^3.7.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/popins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/popins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/popins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/popins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/popins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/popins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/popins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/popins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/popins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/popins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/popins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/popins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/popins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/popins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/popins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/popins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Syne
      fonts:
        - asset: assets/fonts/syne/Syne-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/syne/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/syne/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/syne/Syne-Medium.ttf
          weight: 500      
        - asset: assets/fonts/syne/Syne-Regular.ttf
          weight: 400  
    - family: Arial
      fonts:
  # Regular styles
        - asset: assets/fonts/arial/ARIAL.ttf
          weight: 400
        - asset: assets/fonts/arial/ARIALBD.ttf
          weight: 700
        - asset: assets/fonts/arial/ARIBLK.ttf
          weight: 800
        - asset: assets/fonts/arial/ARIALN.ttf
          weight: 400
        - asset: assets/fonts/arial/ARIALNB.ttf
          weight: 700
        - asset: assets/fonts/arial/ArialCE.ttf
          weight: 400
        - asset: assets/fonts/arial/arialceb.ttf
          weight: 700
        - asset: assets/fonts/arial/ArialCEMTBlack.ttf
          weight: 900
        - asset: assets/fonts/arial/ARIALLGT.ttf
          weight: 300
        - asset: assets/fonts/arial/ArialMdm.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/MontserratAlternates-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/MontserratAlternates-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/MontserratAlternates-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/MontserratAlternates-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/MontserratAlternates-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/MontserratAlternates-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/MontserratAlternates-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/MontserratAlternates-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Plain
      fonts:
        - asset: assets/fonts/plain/Plein-Black.otf
          weight: 900
        - asset: assets/fonts/plain/Plein-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/plain/Plein-Bold.otf
          weight: 700
        - asset: assets/fonts/plain/Plein-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/plain/Plein-Italic.otf
          style: italic
        - asset: assets/fonts/plain/Plein-Light.otf
          weight: 300
        - asset: assets/fonts/plain/Plein-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/plain/Plein-Medium.otf
          weight: 500
        - asset: assets/fonts/plain/Plein-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/plain/Plein-Regular.otf
          weight: 400
    - family: Author
      fonts:
        - asset: assets/fonts/author/Author-Bold.otf
          weight: 700
        - asset: assets/fonts/author/Author-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/author/Author-Extralight.otf
          weight: 200
        - asset: assets/fonts/author/Author-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/author/Author-Italic.otf
          style: italic
        - asset: assets/fonts/author/Author-Light.otf
          weight: 300
        - asset: assets/fonts/author/Author-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/author/Author-Medium.otf
          weight: 500
        - asset: assets/fonts/author/Author-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/author/Author-Regular.otf
          weight: 400
        - asset: assets/fonts/author/Author-Semibold.otf
          weight: 600
        - asset: assets/fonts/author/Author-SemiboldItalic.otf
          weight: 600
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  
